### ISSUE TITLE
SD card

### ISSUE THREAD

**Issue by jamine16** [Flee-Time/F_Light#2]
Have you considered add an SD card module for storage?

Thanks

**Comment by Flee-Time** [comment]
Yes adding an sd card module is in the roadmap for now, using the sdmmc pins would be an issue since the whole pinouts would need to change, for now i intend to use a simple spi sdcard but in the future switching to the native sdmmc pins on the stm32f411ce would be a better option.

**Comment by Flee-Time** [comment]
sdcard support has been added in the latest rtos version. The rtos version has a long way to go to become completely usable. Currently the app system, date and time app, and the sd card filesystem support is working.
